baseURL = "https://pauloroger.dev/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Paulo Roger | DevOps Consultant"

_merge = "none"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Paulo Roger"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  description = "Paulo Roger's Page"
  bio = "Consultant  \nDevOps"
  avatar = "img/photo.webp"
  qrcode = "img/vCard.png"
  vcard = "pauloroger.vcf"
  favicon = "img/favicon.webp"
  error404 = "There is no such page."

  [params.contact]
    # the default fontawesome style in simple key-value pairs is "fab", i.e. brand icons
    github = "https://github.com/paulo-roger"
    [params.contact.email]
      name = "email"
      icon = "envelope"
      style = "fas"
      link = "mailto:me@pauloroger.dev"
    # [params.contact.jabber]
    #   name = "jabber"
    #   icon = "comments"
    #   style = "fas"
    #   link = "xmpp:me@pauloroger.dev"
    [params.contact.mastodon]
      style = "fab"
      link = "https://hachyderm.io/@pauloroger"
      rel-me = true
    [params.contact.resume]
      icon = "address-card"
      link = "https://cv.pauloroger.dev"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      inline = true
      KeepVarNames = false
      keepComments = false
    [minify.tdewolff.html]
      inline = true
      keepComments = false
      keepConditionalComments = false
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepSpecialComments = false
      keepWhitespace = false
      templateDelims = ['', '']
    [minify.tdewolff.js]
      inline = true
      keepVarNames = false
      keepComments = false
      precision = 0
      version = 2022
    [minify.tdewolff.json]
      inline = true
      keepNumbers = false
      precision = 0
    [minify.tdewolff.svg]
      inline = true
      keepComments = false
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.115.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

